### ISSUE TITLE
Not working caused by new name of Galileo Press

### ISSUE THREAD

**Issue by thwfreak** [kriegaex/Galileo-Openbook-Cleaner#26]
Software isn't working caused by the new URL of the openbooks:

`http://openbook.galileo-press.de/` => `https://www.rheinwerk-verlag.de/openbook/`

**Comment by kriegaex** [comment]
Yes, I read about that on *Heise.de* a while ago. Unfortunately I am quite busy at the moment, so I cannot provide a quick fix. I will take care of this issue as soon as I am a little less busy. In the meantime I encourage you to fix the URLs in the source code by yourself. If you know how to do a Maven build, it should be straightforward.

**Comment by overflyer87** [comment]
Hi,

has your schedule shown any improvement so you could take on fixing named issue? I really like your tool and without you I would have never really gotten it_handbuch so perfectly in .epub on my tolino shine. Could you please update your tool for handling the new openbook-link and IDs?

Beispeillink: http://openbook.rheinwerk-verlag.de/apps_programmieren_fuer_iphone_und_ipad

Alle IDs:
apps_programmieren_fuer_iphone_und_ipad windows_server_2012r2 it_handbuch visual_csharp_2012 einstieg_vb_2012 ubuntu linux java7 apps_entwickeln_fuer_iphone_und_ipad javainsel ubuntu_1104 einstieg_vb_2010 ubuntu_1004 c_von_a_bis_z photoshop_cs4 oop linux_unix_programmierung visualbasic_2008 joomla15 visual_csharp einstieg_vb_2008 ruby_on_rails hdr_fotografie excel_2007 javascript_ajax microsoft_netzwerk dreamweaver8 actionscript_einstieg photoshop_cs2 vmware shell_programmierung php_pear actionscript unix_guru
 

Danke! THX!

over

**Comment by kriegaex** [comment]
Just two days after your initial request there has been a [pull request](https://github.com/kriegaex/Galileo-Openbook-Cleaner/pull/27) addressing the issue. I am too busy at the moment to take care of Openbook Cleaner, but you may want to try the PR. I guess it might solve your problem.

**Comment by kriegaex** [comment]
I have just pushed an update to master. If you know how to do a Maven build, you should be fine. Sorry for the delay, the project is no longer actively maintained. But maybe in the next few days I can take a look at the changed books (almost all MD5s have changed, so there might be regressions due to changed layouts, e.g. I just saw links to feedback forms in some books which should be removed by the cleaner).

**Comment by kriegaex** [comment]
Update: The download link on the main project page now points to a [development snapshot](http://scrum-master.de/download/GalileoOpenbookCleaner/openbook_cleaner-1.2.0-SNAPSHOT.jar), so you do not have to build the tool by yourself.
