### ISSUE TITLE
Windows Server 2012 R2 openbook is missing

### ISSUE THREAD

**Issue by NetRat88** [kriegaex/Galileo-Openbook-Cleaner#28]
Cold you please add the Windows Server 2012 R2 openbook to the config.xml?
http://openbook.rheinwerk-verlag.de/windows_server_2012r2/

If there is no direct link available, is it possible to convert an already downloaded openbook. Because you can also find the openbook from wintotal:
http://www.wintotal.de/softwarearchiv/?id=6991

Best regards

**Comment by kriegaex** [comment]
You could have done that by yourself, see #30 and usage help. I have just pushed an update to master which adds the new book.

P.S.: If you do not understand German in the other ticket, please let me know.

**Comment by kriegaex** [comment]
Update: The download link on the main project page now points to a [development snapshot](http://scrum-master.de/download/GalileoOpenbookCleaner/openbook_cleaner-1.2.0-SNAPSHOT.jar), so you do not have to build the tool by yourself.
