### ISSUE TITLE
Erfassen und Hinzufügen von neuen Releases?

### ISSUE THREAD

**Issue by Dracon23** [kriegaex/Galileo-Openbook-Cleaner#30]
Ist das ´manuelle hinzufügen neuer Bücher aus dem Openbooks-Katalog irgendwie möglich?

**Comment by kriegaex** [comment]
Ja, einfach mit Option `--write-config` bzw. `-w` die mitgelieferte _config.xml_ als lokale Datei herausschreiben, neues Buch mit entsprechenden Angaben einfügen und OpenbookCleaner nochmals starten.

Aktuell müßtest Du am Ende diesen `<entry>` einfügen:

```
  <entry>
    <id>WINDOWS_SERVER_2012</id>
    <book>
      <title>Windows Server 2012 R2</title>
      <unpackDirectory>windows_server_2012</unpackDirectory>
      <downloadArchive>http://download2.galileo-press.de/openbook/galileocomputing_windows_server_2012r2.zip</downloadArchive>
      <archiveMD5>8d8094f20542282184794f15ccbf0e5a</archiveMD5>
      <coverImage>http://cover.galileo-press.de/9783836220132.jpg</coverImage>
    </book>
  </entry>
```

Wenn Du den aktuellen *master* (gerade gepusht) auscheckst und baust, ist die Konfiguration aber aktuell. Ich habe auch umgebaut von Galileo auf Rheinwerk.

**Comment by kriegaex** [comment]
Update: Der Download-Link auf der Hauptseite des Projekts zeigt nun auf einen [Development Snapshot](http://scrum-master.de/download/GalileoOpenbookCleaner/openbook_cleaner-1.2.0-SNAPSHOT.jar), wodurch das Bauen für Dich entfällt, Du kannst direkt so testen.

**Comment by Dracon23** [comment]
Super, danke dir ;)
