### ISSUE TITLE
Feature: epub-Generierung

### ISSUE THREAD

**Issue by hoeppie** [kriegaex/Galileo-Openbook-Cleaner#32]
Hallo Alexander,
erstellst du ein Update zum Download von der aktuellen
Web-Seite?
Gruß Dirk

**Comment by kriegaex** [comment]
Was geht denn nicht? Wie wäre es mit einer Fehlermeldung und gern auch einem Hinweis, was sich geändert haben soll?

**Comment by hoeppie** [comment]
Hallo,
war blöd formuliert und auch die falsche Kategorie.
Wir hatten mal vor ein paar Jahren Kontakt und war die Idee gleich ein eBook
zu erstellen. Ich hatte mir damals mit Callibre geholfen, aber das hat irgendwie kein
Anständiges Inhaltsverzeichnis erstellt.
Mit Update meinte ich ob die Idee gibt das ganz in Richtung epub zu bringen.
Gruß Dirk

**Comment by kriegaex** [comment]
Hi Dirk. Nein, das hatte ich nie vor. Dafür gibt es separate Werkzeuge.

**Comment by hoeppie** [comment]
Magst du die Online-Bücher von http://greenteapress.com/wp/ hinzufügen. Sie gibt es auch als PDF, aber als sauberes HTML wären sie ein Gewinn.
Gruß Dirk

**Comment by kriegaex** [comment]
Lieber Dirk, Du hast jetzt zum zweiten Mal das Thema des Tickets geändert. Erst ging es um Galileo vs. Rheinwerk, dann um ePub (woraufhin ich nachträglich die Überschrift geändert habe) und nun um völlig andere Online-Bücher. Bitte erzeuge lieber ein neues Ticket für ein neues Thema. Dieses Hijacking mag ich nicht so gern, da findet man ja gar nichts mehr.

Abgesehen davon, möchte ich die Bücher von Green Tea Press nicht hinzufügen aus zwei Gründen: Erstens sind die PDFs bereits sauber layoutet und frei von Werbung. Zweitens sehe ich keine ZIP-Downloads für die HTML-Versionen. Mein bearbeitet die Bücher ja offline nach dem Download. Da müßte ich zusätzlich noch einen Web Crawler schreiben oder einbinden. Ich sehe den Mehrwert nicht, PDF ist doch super zu lesen mit Mobilgeräten.

**Comment by hoeppie** [comment]
Lieber Alexander,
sorry, tut mir leid. Danke dir für das Ändern des Topics. Es sind gerade meine ersten Schritte im Github.
Danke für die Ausführlich Antwort. Dann werde ich halt selbst Hand anlegen.
PDFs auf eBookReaden sind  Restriktionen unterworfen, die es nicht gerade angenehm machen, sie dort zu lesen. Ich habe ein Tolino und Trekstore Reader und beide machen mit PDF Probleme. Sei es
im Anpassend er Schrift, der Größe der Vorlage usw,
