### ISSUE TITLE
Build mit Java 11

### ISSUE THREAD

**Issue by StefRe** [kriegaex/Galileo-Openbook-Cleaner#35]
Das die internen jars wie z.B. tools.jar ab Java 9 nicht mehr verfügbar sind, mußte ich folgendes in pom.xml ergänzen:

```
        <dependency>
            <groupId>com.sun</groupId>
            <artifactId>tools</artifactId>
            <version>${java.version}</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/pom.xml</systemPath>
        </dependency>
```
[Quelle](https://stackoverflow.com/a/49474325/3944322)

**Comment by kriegaex** [comment]
Entschuldige bitte, dass ich so lange nicht daran gedacht habe, dieses Problem zu beheben, aber von Dir kam zu den anderen Themen auch kein Feedback mehr. Ich habe das Problem aber anders gelöst als mit dem von Dir vorgeschlagenen Workaround. Es ist nicht so gut, _tools.jar_ einer älteren Java-Version mit einem neueren JDK zu benutzen. Das Problem lag am AspectJ Maven Plugin, das seit Jahren nicht aktualisiert wurde auf Kompatibilität zu Java 9+ und AspectJ 1.9.x. Es gibt aber einen gut gepflegten Fork.

**Comment by StefRe** [comment]
Für mich war das Thema eigentlich erledigt, da ich das Buch ja herunterladen konnte. Mein Hinweis (erst unter #33, dann wunschgemäß als neues Issue #35 hier angelegt) war nur für alle diejenigen gedacht, die das Programm auch mit Java11 nutzen wollen.

**Comment by kriegaex** [comment]
Ich meinte eher Feedback bzw. Re-Test zu #36. 😉

**Comment by JavaMarcel** [comment]
Sry für meine Unwissenheit...

Ich versuche seit kurzer Zeit mir Java anhand von Video Kursen beizubringen, bin aber grade erst bei den Grundlagen.
Da ich das Java Buch auch sehr Praktisch fände, fand ich hier diese Anleitung.
Leider verstehe ich nicht viel... Vorallem nicht, was ist GOC ? Per Google usw. konnte ich das nicht heraus finden.

Daher kann ich die Anleitung auch nicht wirklich verwenden. 
Ich habe Winhttrack benutzt und habe das Buch als whtt Datei.

Nun ich wüsste gern, was ist GOC? und wo muss ich was wie Öffnen?
Vielen Dank

**Comment by kriegaex** [comment]
GOC ist lediglich eine Abkürzung für den Namen des Projekts: Galileo OpenBook Cleaner. Zwar heißen die Bücher inzwischen nicht mehr wie zuvor Galileo OpenBooks, weil der Verlag aufgekauft wurde vom Rheinwerk Verlag, aber ich habe mir nicht die Mühe gemacht, das Projekt deswegen umzubenennen.
