### ISSUE TITLE
Code-Formatierung im `java_8` Buch

### ISSUE THREAD

**Issue by StefRe** [kriegaex/Galileo-Openbook-Cleaner#36]
Hallo Alexander,
Vielen Dank für das großartige Programm. Mit dem aktuelle snapshot von `parse-online-books` funktioniert es gut, bis auf die Formatierung der Codeblöcke - hier wird die erste Zeile eingerückt und es werden zusätzliche Leerzeilen eingefügt:
![grafik](https://user-images.githubusercontent.com/19879328/70815837-8c262500-1dce-11ea-869b-d6f68be4a5c5.png)   ![grafik](https://user-images.githubusercontent.com/19879328/70815900-a8c25d00-1dce-11ea-9ce7-a8c7b6dc3442.png)
(links [original](http://openbook.rheinwerk-verlag.de/javainsel/01_002.html#u1.2.9), rechts konvertiert)

Läßt sich das relativ einfach beheben?

**Comment by kriegaex** [comment]
Das Problem ist, dass das kein Codeblock, z.B. `<pre>`, ist sondern etwas manuell Formatiertes mit Zeilenumbrüchen, das im Original so aussieht:

```html
<div class="listing" id="l_ohne_01_00">#include &lt;cstring&gt;<br></br>#include &lt;iostream&gt;<br></br><br></br>using namespace std;<br></br><br></br>class VeryUnsafe {<br></br>public:<br></br>  VeryUnsafe() { strcpy( password, "HaL9124f/aa" ); }<br></br>private:<br></br>  char password[ 100 ];<br></br>};<br></br>int main() {<br></br>  VeryUnsafe badguy;<br></br>  char *pass = reinterpret_cast&lt;char*&gt;( &amp; badguy );<br></br>  cout &lt;&lt; "Password: " &lt;&lt; pass &lt;&lt; endl;<br></br>}</div>
```

Der Cleaner säubert nicht nur sondern formatiert auch den gesäuberten Quellcode neu, so dass es hinterher so aussieht:

```html
    <div class="listing" id="l_ohne_01_00">
      #include &lt;cstring&gt; 
     <br> 
     <br>#include &lt;iostream&gt; 
     <br> 
     <br> 
     <br> 
     <br>using namespace std; 
     <br> 
     <br> 
     <br> 
     <br>class VeryUnsafe { 
     <br> 
     <br>public: 
     <br> 
     <br> VeryUnsafe() { strcpy( password, "HaL9124f/aa" ); } 
     <br> 
     <br>private: 
     <br> 
     <br> char password[ 100 ]; 
     <br> 
     <br>}; 
     <br> 
     <br>int main() { 
     <br> 
     <br> VeryUnsafe badguy; 
     <br> 
     <br> char *pass = reinterpret_cast&lt;char*&gt;( &amp; badguy ); 
     <br> 
     <br> cout &lt;&lt; "Password: " &lt;&lt; pass &lt;&lt; endl; 
     <br> 
     <br>} 
    </div> 
```

So weit, so gut. Allerdings ist dann - das siehst Du hier nicht - im CSS die Einstellung `white-space: pre-wrap;` zu finden. Mehr dazu [hier](https://css-tricks.com/almanac/properties/w/whitespace/). Kurz gesagt, führt es dazu, dass innerhalb der so ausgezeichneten Blocks für die Klasse `.listing` plötzlich Whitespace so behandelt wird, als wäre ein `<pre>` Block vorhanden, nur dass es zusätzlich Wortumbruch gibt. Wenn ich z.B. in den Entwickler-Tools des Browsers die `white-space`-Eigenschaft vorübergehend deaktiviere, sieht der "Codeblock" so aus, wie er soll. (Ich erkläre das alles auch, um für mich selbst laut nachzudenken.) *Update:* Na ja, er sieht nicht ganz aus, wie er soll, denn die Einrückungen im Code selbst sind dann auch weg.

Am einfachsten wäre es wohl, den Cleaner das CSS anpassen zu lassen. Danach wäre allerdings zu prüfen, ob sich das irgendwo anders negativ auswirkt. Ich hoffe nicht. Ob und wann ich dazu komme, weiß ich noch nicht, ich mache kaum noch etwas am Openbook Cleaner. Aber demnächst sollte ich mal Zeit haben.

Ich habe das nachgeprüft in einer älteren (früher heruntergeladenen) Kopie des `java_8` Buches, dort heißt die CSS-Datei _rw_open.css_. In Zeile 209 änderst Du einfach `white-space:pre-wrap;` in `white-space:wrap;`, wenn Du meine Erklärung nachvollziehen willst.

Noch eine Info an mich selbst: Das Buch `java_8` ist das einzige, in dem das CSS `white-space: pre-wrap;` oder `white-space: pre;` enthält, abgesehen von einem anderen Buch, wo es aber für `<pre>` Elemente redundant gesetzt wird.

**Comment by kriegaex** [comment]
Jetzt bin ich verwirrt. Mein altes Archiv enthält ein Java-8-Buch, aber mit der aktuellen Version enthält keines der Bücher JAVA_INSEL und JAVA_7 das problematische CSS. Kannst Du mir bitte die ID des Buches sagen, das Du herunterlädtst bzw. die Kommandozeile, mit der Du den Cleaner startest? Ich wollte gerade kurz eine alternative Idee für einen Fix ausprobieren.

**Comment by StefRe** [comment]
httrack.exe http://openbook.rheinwerk-verlag.de/javainsel/ -O ./java_8 -%v
-*.zip


Am Mo., 16. Dez. 2019 um 03:24 Uhr schrieb Alexander Kriegisch <
notifications@github.com>:
